[platformio]
default_envs = esp32dev

[env]
platform = espressif32
framework = arduino, espidf
monitor_speed = 115200

[env:esp32dev]
board = esp32dev
board_build.esp-idf.sdkconfig_path = sdkconfig.esp32dev
build_flags =
  -DSWITCH_AUTO_DRAW_USE_CLASSIC_BT=1

[env:esp32-s3-devkitc-1]
board = esp32-s3-devkitc-1
build_flags =
  -DSWITCH_AUTO_DRAW_USE_CLASSIC_BT=1
